name: New Issue
description: Description
title: "[Create New Issue]: "
labels: ["IWOC2024"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make an issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a brief description
      placeholder: Please include a summary. Please also include relevant motivation and context. 
      value: "Description"
  - type: dropdown
    id: contribtype
    attributes:
      label: Type of Contribution
      multiple: true
      options:
        - Enhancement
        - Feature Addition
        - Feature Update
        - UI Fix
        - Documentation
        - Improvements
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I follow [Contributing Guidelines](https://github.com/hariketsheth/Article_Repository_Management_System/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/hariketsheth/Article_Repository_Management_System/blob/main/CODE_OF_CONDUCT.md) of this project.
          required: true
