name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: hariketsheth/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{github.actor}}, <br> Thank you for opening an issue. :octocat: <br> Note - Self-assigns by the original author will be prioritised by mentors manually<br> To get assigned to this particular issue please use <b>/assign</b><br><i> Check this <a href="https://github.com/hariketsheth/Article_Repository_Management_System/CONTRIBUTING.md">guide</a> before contributing.'
